# ---
# title: "OHLC Data"
# author: "Ian Fayorsey"
# date: ""
# output: html_document
# ---

```{r, Packages}
#Packages
packages <- c('dplyr' ,'magrittr' ,'tidyr' ,'tibble','readr','foreach',
  'doParallel','purrr','tidyverse','stringr','gtable','plyr',
  'httr','binancer','randomForest','keras','TTR','pROC',
  'GA','ggplot2','grid','gridExtra','gtable','corrplot','xtable',
  'dygraphs','caret','lubridate','zoo','timeSeries','timetk','TTR',
  'xts','tidyquant','TSstudio','QuantTools','spatialEco','knitr',
  'Hmisc','htmltools','blastula')

install.packages(packages)
suppressMessages(invisible(lapply(packages, library, character.only = TRUE)))

options(scipen = 999)


cl  <- parallel::makeCluster(3, setup_timeout = 0.5)
doParallel::registerDoParallel(cl)

future::plan(future::multisession)
```

```{r, Options}
key <- ''
  
secret <- ''

binance_credentials(key, secret)

ticker <-  unique(sort(c('BTC', 'LTC','BCH','BSV','XMR','DASH','ZEC','DBG','MONA','KMD','ETN','MET','GAS','WBTC','XTZ','NEO','ETC','WAVES','ONT','ZIL','DOT','KSM','ZRX','OCT','TRB','NEXT','MIS','THETA','OCEAN','DNA','COMP','NEXO','PMA','MLT','ABBC','IOTX','TRAC','HT','OKB','KNC','LRC','SRM','GNO','NMR','HEDG','LIT','STORJ','YFI','CREAM','LINA','DYP','AVAX','MOON','LIMIT','POWER','SNX','UMA','FTX','CVP','MDS','RSV','AMPL','CEL','ZEN','CVC','ZEN','XLM','SUSHI', 'BNB', 'ETH', 'BAND', 'EOS', 'ADA', 'TRX', 'NEAR', 'CHZ', 'FIL', 'LTCUP', 'ALGO', 'SXP', 'FIO', 'MITH', 'DATA', 'INJ', 'ENJ', 'NEAR', 'EGLD', 'RSR', 'LINK', 'VET', 'UNI', 'AAVE', 'BQX', 'AAVE', 'XEM', 'DOCK', 'LTO', 'MFT', 'NAV', 'OMG', 'ONT','PAX' ,'PIVX','RCN', 'REN', 'TFUEL', 'XVS', 'BAL', 'CEL', 'MKR', 'QTUM', 'IOTA')));ticker


binancePairs <- sort(binance_symbols())

btcCoins <- paste0(ticker, 'BTC')
ethCoins <- paste0(ticker, 'ETH')
usdtCoins <- paste0(ticker, 'BUSD')
bnbCoins <- paste0(ticker, 'BNB')

allCoins <- c(btcCoins, ethCoins, bnbCoins, usdtCoins)

allpairs <- sort(foreach( i = allCoins, .combine = c) %do% {
  binancePairs[grepl(i, binancePairs)];
})
 
remove <- c('RENBTCBTC', 'RENBTCETH', 'STORJETH', 'AMBNB',
            'CVCBNB', 'DAIBNB', 'DIABTC', "DOCKETH","TRBBNB",
            'ZRXBNB', 'BALBNB')
 
allpairs <- allpairs[!allpairs %in% remove]

ethpairs <- allCoins[grepl('BTC', allpairs)];
ethpairs <- allCoins[grepl('ETH', allpairs)];
bnbpairs <- allpairs[grepl('BNB', allpairs)];
usdtpairs <- allpairs[grepl('BUSD', allpairs)];


interval <- "1h"

endDate <- Sys.time(); endDate
startDate <- endDate - hours(500); 
USDT_amount <-60
ETH_amount <- .2
BNB_amount <- 3
BTC_amount <- .006

```

```{r, Pairs}
# USDT = 1; ETH = 2, BNB = 3, BTC = 4, ALL = 5
trigger <- 1
plot_trigger <- 1
```

```{r, Modeling}
# Downloading candlesticks -----------------------------------------------------------------------------------------------------------

if(trigger == 1) {
  pairTrade <- usdtpairs
  pairAmount <- USDT_amount
} else {
  if (trigger == 2) {
    pairTrade <- ethpairs
    pairAmount <- ETH_amount
    } else {
      if (trigger == 3) {
        pairTrade <- bnbpairs
        pairAmount <- BNB_amount
      } else {
        if (trigger == 4) {
          pairTrade <- btcpairs
          pairAmount <- BTC_amount
        } else {
          if (trigger ==  5) {
          pairTrade <- allpairs
          pairAmount <- 1
          }
        }
      }
    }
}

starter <- Sys.time()
#Single pairing 3 month historical candles
getCandles <-  function(symbol, interval, startDate, endDate){
  
  #initial API call
  data <- binance_klines(symbol = symbol, interval = interval, start_time = startDate, end_time = endDate)
  # data <- binance_ticks(symbol = 'ETCUSDT')
  cat(paste0(symbol, " ", interval, ' OHLCs downloaded. \n'))
  #data = arrange(data, open_time)
  return(data)
}



# Get candlesticks for multiple trading pairs
getPairs <- function(pairs, interval, startDate, endDate){
  

  start_timer = Sys.time()
  data <- foreach(i = 1:length(pairs), .packages = c("foreach", 'binancer', "lubridate", 'dplyr'), .export = c('getCandles'), .verbose = F, .errorhandling = 'remove') %dopar% {
    
    symbol <- pairs[i]
    temp_data <- getCandles(symbol = symbol, interval = interval, startDate = startDate, endDate = endDate)
    
    return(temp_data)
  }
  
  # names(data) <- pairs
  end_timer = Sys.time()
  time_taken = end_timer - start_timer
  cat(paste0(length(data), " pairs downloaded in ", time_taken, " as R object"), '\n')
  
  
  return(data)

}



```

```{r, Execution}
# Execution -----------------------------------------------------------------------------------------------------------------
sampleData <- getPairs(pairTrade, interval, startDate = startDate, endDate = endDate)

names(sampleData) <- foreach( i = 1:length(sampleData), .combine = c) %do%{
  sampleData[[i]]$symbol[1]
}

```